/** Public CV asset paths (generated by `npm run generate-cv`). */
export const CV_PDF_PATH = '/Derrick-Teye-CV.pdf';
export const CV_PDF_FILENAME = 'Derrick-Teye-CV.pdf';
export const CV_PDF_LEGACY_PATH = '/Riley-Happuch-CV.pdf';
